(async function(){
  const projectBase=new URL((window.COA_CONFIG||{}).projectBase||'./',window.location.href);const manifestUrl=window.COA_PROJECT_MANIFEST||new URL('project.json',projectBase).href;const response=await fetch(manifestUrl,{cache:'no-store'});if(!response.ok)throw new Error(`project.json não encontrado (HTTP ${response.status})`);const project=await response.json();
  document.title=`RC | ${project.farm||project.field||'WebGIS'}`;document.getElementById('mapTitle').textContent=[project.company,project.farm,project.field_code||project.field].filter(Boolean).join(' • ');
  const fields=[['Empresa',project.company],['Fazenda',project.farm],['Talhão',project.field_code||project.field],['Cultura',project.crop],['Data',project.survey_date]];document.getElementById('identity').innerHTML=fields.filter(x=>x[1]).map(x=>`<div><strong>${COA.escape(x[0])}:</strong> ${COA.escape(x[1])}</div>`).join('');
  const s=project.statistics||{},metrics=[['Área',s.area_ha!=null?`${Number(s.area_ha).toLocaleString('pt-BR')} ha`:null],['Falhas',s.failure_count],['Comprimento',s.failure_length_m!=null?`${Number(s.failure_length_m).toLocaleString('pt-BR')} m`:null],['Falhas/ha',s.failure_m_per_ha!=null?`${Number(s.failure_m_per_ha).toLocaleString('pt-BR')} m/ha`:null],['Linhas',s.total_row_length_m!=null?`${Number(s.total_row_length_m).toLocaleString('pt-BR')} m`:null],['Falha linear',s.failure_percentage!=null?`${Number(s.failure_percentage).toLocaleString('pt-BR')}%`:null]];document.getElementById('indicators').innerHTML=metrics.filter(x=>x[1]!=null).map(x=>`<div class="metric"><span>${x[0]}</span><strong>${x[1]}</strong></div>`).join('')||'<span>Sem indicadores.</span>';
  const map=COA.createMap(project);map.on('load',async()=>{try{const queryable=await COA.addProjectLayers(map,project);COA.enablePopups(map,queryable);COA.enableMeasures(map);COA.fitProject(map,project);}catch(error){console.error(error);document.getElementById('mapTitle').textContent=`Falha ao carregar camadas: ${error.message}`;}});
  document.getElementById('menuButton').onclick=()=>document.getElementById('sidebar').classList.toggle('closed');document.getElementById('fitButton').onclick=()=>COA.fitProject(map,project);
  if(new URLSearchParams(location.search).get('qr')==='1'&&window.QRCode){const overlay=document.createElement('div');overlay.style='position:fixed;inset:0;z-index:100;background:#000b;display:grid;place-items:center';const card=document.createElement('div');card.style='background:white;color:#17302f;padding:24px;border-radius:12px;text-align:center';card.innerHTML='<h2>Compartilhar mapa</h2><canvas id="coaQr"></canvas><p>Toque fora para fechar</p>';overlay.append(card);document.body.append(overlay);QRCode.toCanvas(document.getElementById('coaQr'),location.href.replace(/[?&]qr=1/,'').replace(/\?$/,''),{width:260,margin:2});overlay.onclick=e=>{if(e.target===overlay)overlay.remove();};}
})().catch(error=>{console.error('[RC WebGIS] Não foi possível carregar os dados deste projeto.',error);document.body.innerHTML=`<main class="startup-error" style="padding:2rem"><h1>Não foi possível carregar os dados deste projeto.</h1><p>${String(error.message)}</p><p>Use o botão PRÉ-VISUALIZAR do plugin para iniciar o servidor local.</p></main>`;});
