window.COA = window.COA || {};
COA.projectUrl = function(path) {
  const projectBase = new URL((window.COA_CONFIG || {}).projectBase || './', window.location.href);
  return new URL(String(path || '').replace(/^\/+/, ''), projectBase).href;
};
COA.rasterFiles = async function(project, layer) {
  console.info('[COA Raster] arquivos:', project.orthomosaic);
  if (project.orthomosaic && project.orthomosaic.enabled !== false && Array.isArray(project.orthomosaic.files)) {
    return project.orthomosaic.files.slice();
  }
  // Compatibility with project.json generated by 0.3.0 and earlier.
  if (layer.format === 'raster_pmtiles') return [layer.output];
  if (layer.format === 'raster_pmtiles_mosaic') {
    const indexUrl = new URL(COA.projectUrl(layer.output));
    const response = await fetch(indexUrl.href, {cache: 'no-store'});
    if (!response.ok) throw new Error(`Índice do ortomosaico não encontrado: ${layer.output}`);
    const mosaic = await response.json();
    return (mosaic.tiles || []).map(tile => new URL(tile.file, indexUrl).href);
  }
  return [];
};
COA.addProjectLayers = async function(map, project) {
  const queryable = [];
  const enabled = (project.layers || []).filter(layer => layer.enabled && layer.output);
  const visualPriority = {orthomosaic: 0, boundary: 1, failures: 2, lines: 3, points: 4};
  const ordered = enabled.slice().sort((a, b) =>
    (visualPriority[a.role] ?? 10) - (visualPriority[b.role] ?? 10)
  );
  for (const [index, layer] of ordered.entries()) {
    const id = `coa-${layer.role}-${index}`;
    const mapIds = [];
    if (layer.format === 'raster_pmtiles' || layer.format === 'raster_pmtiles_mosaic') {
      const files = await COA.rasterFiles(project, layer);
      if (!files.length) throw new Error('Manifesto do ortomosaico não contém arquivos PMTiles.');
      for (const [partIndex, file] of files.entries()) {
        const partId = `orthomosaic-${partIndex}`;
        const resolvedUrl = /^https?:\/\//i.test(file)
          ? file
          : COA.projectUrl(file);
        console.info('[COA Raster] URL:', resolvedUrl);
        console.info('[COA Raster] criando source', partId, resolvedUrl);
        map.addSource(partId, {
          type: 'raster', url: `pmtiles://${resolvedUrl}`, tileSize: 256
        });
        map.addLayer({
          id: partId, type: 'raster', source: partId,
          layout: {visibility: layer.visible ? 'visible' : 'none'},
          paint: {'raster-opacity': 1, 'raster-fade-duration': 0, 'raster-resampling': 'linear'}
        });
        mapIds.push(partId);
      }
    } else if (layer.format === 'vector_pmtiles') {
      map.addSource(id, {type: 'vector', url: `pmtiles://${COA.projectUrl(layer.output)}`});
      const type = layer.geometry_type === 'Point' ? 'circle' : 'line';
      map.addLayer({id, type, source: id, 'source-layer': layer.source_layer,
        layout: {visibility: layer.visible ? 'visible' : 'none'},
        paint: COA.paintFor(type, layer.role, layer.style || {})});
      mapIds.push(id);
      if (layer.queryable) queryable.push(id);
    } else {
      map.addSource(id, {type: 'geojson', data: COA.projectUrl(layer.output), generateId: true});
      const paint = layer.style || {};
      let type = 'line';
      if (layer.role === 'failures') paint['line-width'] = ['interpolate', ['linear'], ['coalesce', ['get', '_coa_length_m'], 0], .5, 2, 5, 5];
      if (layer.geometry_type === 'Point') type = 'circle';
      if (layer.geometry_type === 'Polygon') {
        const fillId = `${id}-fill`;
        map.addLayer({id: fillId, type: 'fill', source: id,
          layout: {visibility: layer.visible ? 'visible' : 'none'},
          paint: {'fill-color': paint['fill-color'] || '#a7d46f', 'fill-opacity': paint['fill-opacity'] ?? .08}});
        mapIds.push(fillId);
      }
      map.addLayer({id, type, source: id, layout: {visibility: layer.visible ? 'visible' : 'none'},
        paint: COA.paintFor(type, layer.role, paint)});
      mapIds.push(id);
      if (layer.queryable) queryable.push(id);
    }
    layer._mapIds = mapIds;
  }
  COA.renderLayerList(map, project.layers || []);
  return queryable;
};
COA.paintFor = function(type, role, paint) {
  if (type === 'circle') return {'circle-color': paint['circle-color'] || '#8e44ad', 'circle-radius': paint['circle-radius'] || 5, 'circle-stroke-color': '#fff', 'circle-stroke-width': 1};
  if (role === 'failures') return {'line-color': ['match', ['get', '_coa_class'], '0,50–1,50 m', '#f4d03f', '1,50–3,00 m', '#3498db', '3,00–5,00 m', '#f39c12', '>= 5,00 m', '#e74c3c', '#f4d03f'], 'line-width': paint['line-width'], 'line-opacity': .95};
  return {'line-color': paint['line-color'] || '#fff', 'line-width': paint['line-width'] || 2, 'line-opacity': paint['line-opacity'] ?? .9};
};
COA.renderLayerList = function(map, layers) {
  const host = document.getElementById('layerList'); host.innerHTML = '';
  layers.filter(layer => layer.enabled).forEach(layer => {
    const row = document.createElement('label'); row.className = 'layer-row';
    const input = document.createElement('input'); input.type = 'checkbox'; input.checked = layer.visible;
    input.onchange = () => (layer._mapIds || []).forEach(id => map.setLayoutProperty(id, 'visibility', input.checked ? 'visible' : 'none'));
    const name = document.createElement('span'); name.textContent = layer.role === 'orthomosaic' ? 'Ortomosaico' : (layer.name || layer.role);
    const swatch = document.createElement('i'); swatch.className = 'swatch';
    swatch.style.background = (layer.style || {})['line-color'] || (layer.style || {})['circle-color'] || '#a7d46f';
    row.append(input, name, swatch); host.append(row);
  });
};
